name: uni_camp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  cloud_firestore: 5.4.4
  json_theme_plus: ^6.6.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  font_awesome_flutter: ^10.8.0
  file_picker: ^8.1.3
  toastification: ^2.3.0
  google_fonts: ^6.2.1
  flutter_map_animations: ^0.7.1
  intl: ^0.19.0
  flutter_carousel_widget: ^3.1.0
  flutter_time_picker_spinner: ^2.0.0
  firebase_storage: ^12.3.6
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/appainter_theme.json

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
          weight: 100  # Thin
        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
          weight: 600  # Semi-Bold
        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
          weight: 700  # Bold
        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
          weight: 800  # Extra Bold
        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
          weight: 900  # Black (Heaviest)
