// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5HHxOIbFwM_20Z3J2AGpQbD7s0eihWM',
    appId: '1:254518558778:web:85584e87a7e358a0d03503',
    messagingSenderId: '254518558778',
    projectId: 'unicamp-78ff6',
    authDomain: 'unicamp-78ff6.firebaseapp.com',
    storageBucket: 'unicamp-78ff6.appspot.com',
    measurementId: 'G-RJPKK7423K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNR62_srtf42oocjPCBrANCcdNT1Ma0Gk',
    appId: '1:254518558778:android:72f7363c7e324b69d03503',
    messagingSenderId: '254518558778',
    projectId: 'unicamp-78ff6',
    storageBucket: 'unicamp-78ff6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9TpVwNgHUfm7k8f_V58I_JzUMDMhVJXA',
    appId: '1:254518558778:ios:724aebcbffa3a363d03503',
    messagingSenderId: '254518558778',
    projectId: 'unicamp-78ff6',
    storageBucket: 'unicamp-78ff6.appspot.com',
    iosBundleId: 'com.example.uniCamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9TpVwNgHUfm7k8f_V58I_JzUMDMhVJXA',
    appId: '1:254518558778:ios:724aebcbffa3a363d03503',
    messagingSenderId: '254518558778',
    projectId: 'unicamp-78ff6',
    storageBucket: 'unicamp-78ff6.appspot.com',
    iosBundleId: 'com.example.uniCamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI5HHxOIbFwM_20Z3J2AGpQbD7s0eihWM',
    appId: '1:254518558778:web:09f3f75ad80bbb51d03503',
    messagingSenderId: '254518558778',
    projectId: 'unicamp-78ff6',
    authDomain: 'unicamp-78ff6.firebaseapp.com',
    storageBucket: 'unicamp-78ff6.appspot.com',
    measurementId: 'G-C5KD38CL46',
  );
}
